---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/25 16:56
---
require "base.util.VectorUtil"
require "base.util.StringUtil"

GameTipNpc = class()
GameTipNpc.TYPE_TIP = 4
GameTipNpc.TYPE_MULI_TIP = 5

function GameTipNpc:ctor(config)
    self.name = config.name
    self.actor = config.actor
    self.vec3 = VectorUtil.newVector3(tonumber(config.x), tonumber(config.y), tonumber(config.z))
    self.yaw = tonumber(config.yaw)
    self.type = tonumber(config.type)
    self.title = config.title
    self.content = config.content
    self:onCreate()
end

function GameTipNpc:onCreate()
    if self.type == GameTipNpc.TYPE_TIP then
        EngineWorld:addSessionNpc(self.vec3, self.yaw, self.type, self.name, self.actor, "body", "", self.content)
    elseif self.type == GameTipNpc.TYPE_MULI_TIP then
        local data = {}
        data.title = self.title
        data.tips = StringUtil.split(self.content, "#")
        EngineWorld:addSessionNpc(self.vec3, self.yaw, self.type, self.name, self.actor, "body", "", json.encode(data))
    end
end

return GameTipNpc