---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/3 0003 16:05
---
ChestRewardConfig = {}
ChestRewardConfig.ChestRewards = {}
ChestRewardConfig.RewardType = {
    GUN_CHIP = 1,
    GUN = 2,
    PROP_CHIP = 3,
    PROP = 4,
    MONEY = 5,
    KEY = 6,
    VIP = 7
}

function ChestRewardConfig:initConfig(rewards)
    for _, reward in pairs(rewards) do
        table.insert(self.ChestRewards, {
            Id = tonumber(reward.Id) or 0,
            Type = tonumber(reward.Type) or 0,
            RewardId = tonumber(reward.RewardId) or 0,
            RewardType = tonumber(reward.RewardType) or 0,
            RedressRewardId = tonumber(reward.RedressRewardId) or 0,
            Count = tonumber(reward.Count) or 0,
            Weight = tonumber(reward.Weight) or 0,
            Time = tonumber(reward.Time) or 0
        })
    end
end

function ChestRewardConfig:getChestRewardByType(type)
    local rewards = {}
    for _, reward in pairs(self.ChestRewards) do
        if reward.Type == type then
            table.insert(rewards, reward)
        end
    end
    return rewards
end

function ChestRewardConfig:getChestRewardId(id)
    for _, reward in pairs(self.ChestRewards) do
        if reward.Id == id then
            return reward
        end
    end
end

return ChestRewardConfig