---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/12/30 0030 12:04
---
Define = {}
Define.Money = {
    DIAMOND = 1,
    GOLD = 2,
    MONEY = 3,
    CHIP = 4
}

Define.UnlockMap = "UnlockMap"
Define.BuyGun = "BuyGun"
Define.UpgradeGun = "UpgradeGun"
Define.QuickUpgradeGun = "QuickUpgradeGun"
Define.BuyProp = "BuyProp"
Define.UpgradeProp = "UpgradeProp"
Define.QuickUpgradeProp = "QuickUpgradeProp"
Define.OpenLotteryChest = "OpenLotteryChest"
Define.SpeedUpGradeArmor= "SpeedUpGradeArmor"
Define.UpArmor= "UpArmor"

return Define