---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/22 0022 10:08
---
GuideArrowConfig = {}

function GuideArrowConfig:initConfig(arrows)
    for _, arrow in pairs(arrows) do
        local initPos = VectorUtil.newVector3(tonumber(arrow.x), tonumber(arrow.y), tonumber(arrow.z))
        EngineWorld:addActorNpc(initPos, tonumber(arrow.yaw), arrow.actor, "", "", "", true, false)
    end
end

return GuideArrowConfig