---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/8 0008 15:50
---
SeasonRewardConfig = {}
SeasonRewardConfig.SeasonRewards = {}

function SeasonRewardConfig:initConfig(rewards)
    for _, reward in pairs(rewards) do
        local data = {}
        data.Id = reward.Id
        data.Type = tonumber(reward.Type)
        data.RealId = tonumber(reward.RealId)
        data.Count = tonumber(reward.Count)
        table.insert(self.SeasonRewards, data)
    end
end

function SeasonRewardConfig:getRewardById(id)
    for _, SeasonReward in pairs(self.SeasonRewards) do
        if SeasonReward.Id == id then
            return SeasonReward
        end
    end
end

function SeasonRewardConfig:getRewardByIds(ids)
    local rewards = {}
    ids = StringUtil.split(ids, "#")
    for _, id in pairs(ids) do
        local reward = SeasonRewardConfig:getRewardById(id)
        if reward ~= nil then
            table.insert(rewards, reward)
        end
    end
    return rewards
end

return SeasonRewardConfig