---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/12 0012 13:05
---
require "property.BaseProperty"

MaxDefenseProperty = class("MaxDefenseProperty", BaseProperty)

function MaxDefenseProperty:onPlayerGet(player)
    player:addMaxDefense(self.config.value)
end

return MaxDefenseProperty