---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/10/29 0029 16:44
---
DBManager = {}
DBManager.caches = {}

function DBManager:addCache(key, data)
    self.caches[key] = data
end

function DBManager:getCache(key)
    return self.caches[key]
end

function DBManager:removeCache(userId)
    local uid = tostring(userId)
    for key, cache in pairs(self.caches) do
        if StringUtil.split(key, "#")[1] == uid then
            self.caches[key] = nil
        end
    end
end

function DBManager:initPlayerData(userId, subKey, data)
    local key = tostring(userId) .. "#" .. subKey
    self:addCache(key, data)
end

function DBManager:savePlayerData(userId, subKey, data, immediate)
    local key = tostring(userId) .. "#" .. subKey
    local cache = self:getCache(key)
    if cache == data then
        return
    end
    self:addCache(key, data)
    HostApi.setDBData(userId, subKey, data, immediate or false)
end

function DBManager:getPlayerData(userId, subKey)
    HostApi.getDBData(userId, subKey)
end

return DBManager