---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2018/12/24 17:47
---

RespawnConfig = {}
RespawnConfig.respawns = {}

function RespawnConfig: init(respawns)
    self:initRespawn(respawns)
end

function RespawnConfig:initRespawn(respawns)
    for _, respawn in pairs(respawns) do
        local item = {}
        item.id = respawn.id
        item.teamId = tonumber(respawn.teamId)
        item.position = VectorUtil.newVector3(tonumber(respawn.x), tonumber(respawn.y), tonumber(respawn.z))
        item.yaw = tonumber(respawn.yaw)
        table.insert(self.respawns, item)
    end
end

function RespawnConfig:randomRespawn(teamId)
    if teamId == nil then
        local id = math.random(1, #self.respawns)
        return self.respawns[id]
    end
    local items = {}
    for id, respawn in pairs(self.respawns) do
        if respawn.teamId == teamId then
            table.insert(items, respawn)
        end
    end
    local id = 1
    if #items > 0 then
        math.randomseed(os.clock() * 1000000)
        id = math.random(1, #items)
        return items[id]
    end

end


return RespawnConfig