---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/10 15:55
---

SupplyItemConfig = {}
SupplyItemConfig.items = {}

function SupplyItemConfig:init(config)
    self:initSupplyItem(config)
end

function SupplyItemConfig:initSupplyItem(config)
    for i, v in pairs(config) do
        local item =
        {
            itemId = tonumber(v.itemId),
            itemType = tonumber(v.itemType)
        }
        self.items[item.itemId] = item
    end
end

function SupplyItemConfig:getTypeById(id)
    local item = self.items[id]
    if not item then
        return 0
    end
    return item.itemType
end

function SupplyItemConfig:isSupply(id)
    return self.items[id] ~= nil
end

return SupplyItemConfig