---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/12/5 0005 9:41
---
require "base.util.class"
require "base.task.ITask"
require "base.task.LuaTimer"

local ICommonTask = class("CommonTask", ITask)

function ICommonTask:onTick(ticks)
    LuaTimer:onTick()
    UserExpManager:tryCalculationExp()
    UserExpManager:trySaveExpResult()
    SeasonManager:trySaveHonorResult()
    ReportManager:tryReportGameData()
end

CommonTask = ICommonTask.new(99999)

return CommonTask