---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaolai.
--- DateTime: 2018/12/19 16:07
---

DbUtil = {}

function DbUtil:getPlayerData(player)
    DBManager:getPlayerData(player.userId, 1)
    DBManager:getPlayerData(player.userId, 2)
end

function DbUtil:saveAllPlayerData()
    if GameMatch.curTick == 0 then
        return
    end
    local players = PlayerManager:getPlayers()
    for _, player in pairs(players) do
        self:savePlayerData(player)
    end
end

function DbUtil:savePlayerData(player, immediate)
    if player == nil then
        return
    end
    if player.isReady == false then
        return
    end
    local data = {}
    data.money = player.hallMoney
    DBManager:savePlayerData(player.userId, 2, json.encode(data), immediate)
end

return DbUtil