---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/9/6 10:03
---

require "base.util.VectorUtil"

ExtraPortalConfig = {}
ExtraPortalConfig.PortalBuildings = {}

function ExtraPortalConfig:init(portals)
    self:initPortal(portals)
end

function ExtraPortalConfig:initPortal(portals)
    for i, portal in pairs(portals) do
        local item = {}
        item.id = portal.id
        item.actor = portal.actor
        item.name = portal.name
        item.portalEntryPos = VectorUtil.newVector3(tonumber(portal.entryX), tonumber(portal.entryY), tonumber(portal.entryZ))
        item.portalEntryYaw = tonumber(portal.entryYaw)
        item.portalExitPos = VectorUtil.newVector3(tonumber(portal.exitX), tonumber(portal.exitY), tonumber(portal.exitZ))
        item.gobackActor = portal.goBackActor
        item.gobackName = portal.goBackName
        item.gobackEntryPos = VectorUtil.newVector3(tonumber(portal.goBackEntryX), tonumber(portal.goBackEntryY), tonumber(portal.goBackEntryZ))
        item.gobackEntryYaw = tonumber(portal.goBackEntryYaw)
        item.payHint = portal.payHint
        item.price = tonumber(portal.price)
        item.time = tonumber(portal.time)
        self.PortalBuildings[item.id] = item
    end
end

function ExtraPortalConfig:getPortalBuildingById(id)
    local portal = self.PortalBuildings[id]
    if portal then
        return portal
    end
    error("portal config error, can't find groupId:" .. id)
end

return ExtraPortalConfig