---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/7/16 10:39
---

require "base.util.VectorUtil"

PortalConfig = {}
PortalConfig.PortalBuildings = {}

function PortalConfig:init(portals)
    self:initPortal(portals)
end

function PortalConfig:initPortal(portals)
    for i, portal in pairs(portals) do
        local item = {}
        item.id = portal.id
        item.actor = portal.actor
        item.name = portal.name
        item.portalEntryPos = VectorUtil.newVector3(tonumber(portal.entryX), tonumber(portal.entryY), tonumber(portal.entryZ))
        item.portalEntryYaw = tonumber(portal.entryYaw)
        item.portalExitPos = VectorUtil.newVector3(tonumber(portal.exitX), tonumber(portal.exitY), tonumber(portal.exitZ))
        item.gobackActor = portal.goBackActor
        item.gobackName = portal.goBackName
        item.gobackEntryPos = VectorUtil.newVector3(tonumber(portal.goBackEntryX), tonumber(portal.goBackEntryY), tonumber(portal.goBackEntryZ))
        item.gobackEntryYaw = tonumber(portal.goBackEntryYaw)
        item.gobackExitPos = VectorUtil.newVector3(tonumber(portal.goBackExitX), tonumber(portal.goBackExitY), tonumber(portal.goBackExitZ))
        item.value = tonumber(portal.value)
        item.price = tonumber(portal.price)
        item.cd = tonumber(portal.cd)
        item.npcActor = portal.npcActor
        item.npcName = portal.npcName
        item.npcPos = VectorUtil.newVector3(tonumber(portal.npcX), tonumber(portal.npcY), tonumber(portal.npcZ))
        item.npcYaw = tonumber(portal.npcYaw)
        item.buildingIds = StringUtil.split(portal.buildingIds, "#")
        self.PortalBuildings[item.id] = item
    end
end

function PortalConfig:getPortalBuildingById(id)
    local portal = self.PortalBuildings[id]
    if portal then
        return portal
    end
    error("portal config error, can't find groupId:" .. id)
end

return PortalConfig