---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 2018/7/25 10:21
---

require "Match"

DBDataListener = {}

function DBDataListener:init()
    BaseListener.registerCallBack(GetDataFromDBEvent, self.onGetDataFromDB)
end

function DBDataListener.onGetDataFromDB(player, role, data)
    player.isReady = true
    player:initDataFromDB(data)
end

return DBDataListener