---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/14 0014 16:15
---
EngineUtil = {}

function EngineUtil.sendEnterOtherGame(rakssid, gameType, targetId, mapId)
    mapId = mapId or ""
    HostApi.sendEnterOtherGame(rakssid, gameType, targetId, mapId)
end

function EngineUtil.sendGotoOtherGame(rakssid, gameType, targetId, mapId)
    mapId = mapId or ""
    HostApi.sendGotoOtherGame(rakssid, targetId, gameType, mapId)
end

function EngineUtil.disposePlatformOrder(userId, orderId, isConsume)
    HostApi.platformOrderDispose(userId, WebService.BlockymodBaseUrl, orderId, isConsume or false)
end

return EngineUtil