---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/28 16:25
---
DbUtil = {}

function DbUtil:getPlayerData(player)
    DBManager:getPlayerData(player.userId, 1)
end

function DbUtil:saveAllPlayerData()
    if GameMatch.curTick == 0 or GameMatch.curTick % 30 ~= 0 then
        return
    end
    local players = PlayerManager:getPlayers()
    for _, player in pairs(players) do
        self:savePlayerData(player)
    end
end

function DbUtil:savePlayerData(player, immediate)
    if player == nil then
        return
    end
    if player.isReady == false then
        return
    end
    local data = {}
    data.money = player.hallMoney
    data.guns = player.guns
    data.teamId = player.teamId
    data.gunSprayPaints = player.gunSprayPaints
    data.specialClothing = player.specialClothing
    DBManager:savePlayerData(player.userId, 1, json.encode(data), immediate)
end

return DbUtil