---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/20 11:05
---
DbUtil = {}
DbUtil.ACTORS_TAG = 1
DbUtil.MONEY_TAG = 2

function DbUtil:getPlayerData(player, subkey)
    DBManager:getPlayerData(player.userId, subkey)
end

function DbUtil:saveAllPlayerData()
    if GameMatch.curTick == 0 or GameMatch.curTick % 30 ~= 0 then
        return
    end
    
    local players = PlayerManager:getPlayers()
    for i, player in pairs(players) do
        self:savePlayerData(player)
    end
end

function DbUtil:savePlayerData(player, immediate)
    if player == nil then
        return
    end

    if player.isReady == false then
        return
    end

    local actors_data = {}
    actors_data.actors = player.actors
    actors_data.lotteryTimes = player.lotteryTimes
    actors_data.LastLoginDay = player.LastLoginDay
    DBManager:savePlayerData(player.userId, DbUtil.ACTORS_TAG, json.encode(actors_data), immediate)

    local money_data = {}
    money_data.money = player.money
    DBManager:savePlayerData(player.userId, DbUtil.MONEY_TAG, json.encode(money_data), immediate)
end

function DbUtil:getDBDataRequire(player,subkey)
    DBManager:getPlayerData(player.userId, subkey)
end

return DbUtil