---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/7/5 20:55
---
require "base.util.VectorUtil"

GameGetEquip = class()

function GameGetEquip:ctor(equipbox, initPos, yaw, actor, effect)
    self.entityId = 0
    self.equipbox = equipbox
    self.initPos = initPos
    self.yaw = yaw
    self.actor = actor
    self.haloEffect = effect
    self.timer = 0
    self.isCreake = false
    self:onCreate()
end

function GameGetEquip:onCreate()
    self.entityId = EngineWorld:addActorNpc(self.initPos, self.yaw, self.actor, "", "idle", self.haloEffect)
    GameManager:onAddGetEquipBox(self)
    if self.equipbox.config.type == 1 then
        local y = self.initPos.y + 2
        EngineWorld:addActorNpc(VectorUtil.newVector3(self.initPos.x, y, self.initPos.z), self.yaw, self.equipbox.config.clothesActor, "", "idle")
    else
        EngineWorld:addEntityItem(
                self.equipbox.config.armsId,
                1,
                0,
                5,
                VectorUtil.newVector3(self.initPos.x + 0.1, self.initPos.y + 1, self.initPos.z + 0.05),
                VectorUtil.ZEOR,
                true,
                true)
        self.isCreake = true
    end
end

function GameGetEquip:onTick()

end

function GameGetEquip:onPlayerHit(player)
    self.equipbox:getEquip(player)
end

function GameGetEquip:onRemove()
    EngineWorld:removeEntity(self.entityId)
end

return GameGetEquip