---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/7/5 9:55
---

GameResourceBuilding = class()

function GameResourceBuilding:ctor(build, initPos, yaw, actor, name)
    self.entityId = 0
    self.build = build
    self.initPos = initPos
    self.yaw = yaw
    self.actor = actor
    self.name = name
    self:onCreate()
end

function GameResourceBuilding:onCreate()
    if self.name == "#" then
        self.name = ""
    end
    local name = self.name .. "=(+" .. self.build.outputIncrement .. ")"
    self.entityId = EngineWorld:addActorNpc(self.initPos, self.yaw, self.actor, name, "idle")
end