---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/9/6 11:17
---

GameExtraPortal = class()

function GameExtraPortal:ctor(config)
    self.entityId = 0
    self.config = config
    self.actor = config.actor
    self.name = config.name
    self.initPos = config.portalEntryPos
    self.yaw = config.portalEntryYaw
    self.time = config.time
    self.price = config.price
    self.timer = 0
    self.portal = nil
    self.isCreate = false
end

function GameExtraPortal:onTick(ticks)
    if self.isCreate == false then
        self.timer = self.timer + 1
        if self.timer >= self.time then
            self:onCreate()
            self.isCreate = true
        end
    end
end

function GameExtraPortal:onCreate()
    self.portal = GamePortal.new(0, 0, self.config)
    self.entityId = EngineWorld:addActorNpc(self.initPos, self.yaw, self.actor, self.name, "idle")
    GameManager:onAddPortal(self)
    MsgSender.sendCenterTips(2, Messages:extraPortalStart())
end

function GameExtraPortal:onPlayerHit(player)
    print(self.config.payHint)
    HostApi.sendCustomTip(player.rakssid, self.config.payHint, "ExtraPortal=" .. tostring(self.entityId))
end

function GameExtraPortal:onPlayerSelected(player)
    local money = player:getCurrency()
    if self.price >= money then
        MsgSender.sendCenterTipsToTarget(player.rakssid, 2, Messages:noMoney())
        return
    end
    player:subCurrency(self.price)
    self.portal:hitPortal(player.rakssid, self.config.portalExitPos)
end

return GameExtraPortal