---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/7/5 15:11
---
require "config.BasicConfig"

GamePromoteResource = class()

function GamePromoteResource:ctor(domain, build)
    self.entityId = 0
    self.domain = domain
    self.build = build
    self.resource = domain.config.privateResource
    self.initPos = build.pos
    self.yaw = build.yaw
    self.actor = build.proNpcActor
    self.name = build.proNpcName
    self:onCreate()
end

function GamePromoteResource:onCreate()
    if self.name == "#" then
        self.name = ""
    end
    local name = self.name .. "=($" .. self.build.price .. ")"
    local pos = BasicConfig:getPosByBasic(self.domain.basicId, self.initPos)
    local yaw = BasicConfig:getYawByBasic(self.domain.basicId, self.yaw)
    self.entityId = EngineWorld:addActorNpc(pos, yaw, self.actor, name, "idle")
    GameManager:onAddPromoteResource(self)
end

function GamePromoteResource:onPlayerHit(player)
    if not self.domain:isDomainPlayer(player) then
        MsgSender.sendCenterTipsToTarget(player.rakssid, 2, Messages:noSelfItem())
        return
    end
    self.domain.resource:promoteResource(player, self)
end

function GamePromoteResource:onRemove()
    EngineWorld:removeEntity(self.entityId)
    GameManager:onRemovePromoteResource(self)
end
