---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/7/16 12:12
---

GamePortalBuilder = class()

function GamePortalBuilder:ctor(portal, initPos, yaw, actor, name)
    self.entityId = 0
    self.portal = portal
    self.initPos = initPos
    self.yaw = yaw
    self.actor = actor
    self.name = name
    self:onCreate()
end

function GamePortalBuilder:onCreate()
    if self.name == "#" then
        self.name = ""
    end
    local name = self.name .. "=($" .. self.portal:getPrice() .. ")"
    self.entityId = EngineWorld:addActorNpc(self.initPos, self.yaw, self.actor, name, "idle")
    GameManager:onAddPortal(self)
end

function GamePortalBuilder:isSamePlayer(player)
    return self.portal:getPlayer() == player
end

function GamePortalBuilder:onPlayerHit(player)
    if self:isSamePlayer(player) == false then
        return
    end
    local price = self.portal:getPrice()
    local money = player:getCurrency()
    if price <= money then
        player:subCurrency(price)
        player.portal = self.portal
        self:onRemove()
        self.portal:buildPortal()
        MsgSender.sendCenterTips(3, Messages:succeedBuildingPortal(player:getDisplayName()))
    else
        MsgSender.sendCenterTipsToTarget(player.rakssid, 2, Messages:noMoney())
    end
end

function GamePortalBuilder:onRemove()
    EngineWorld:removeEntity(self.entityId)
    GameManager:onRemovePortal(self)
end