---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/19 0019 11:37
---
BlockManager = {}
BlockManager.BlockLifeCache = {}
BlockManager.PlayerBlockCache = {}

function BlockManager:clearAllBlock()
    for hash, cache in pairs(BlockManager.PlayerBlockCache) do
        EngineWorld:setBlockToAir(cache.postion)
    end
    BlockManager.BlockLifeCache = {}
    BlockManager.PlayerBlockCache = {}
end

function BlockManager:clearPlayerBlock(player)
    local removes = {}
    for hash, cache in pairs(BlockManager.PlayerBlockCache) do
        EngineWorld:setBlockToAir(cache.postion)
        table.insert(removes, hash)
    end
    for _, remove in pairs(removes) do
        BlockManager.BlockLifeCache[remove] = nil
        BlockManager.PlayerBlockCache[remove] = nil
    end
end

function BlockManager:onPlayerPlaceBlock(player, blockId, blockPos)
    local life = 1
    for _, block in pairs(player.equip_blocks) do
        if block.ItemId == blockId then
            life = block.Life
        end
    end
    local hash = VectorUtil.hashVector3(blockPos)
    BlockManager.BlockLifeCache[hash] = life
    BlockManager.PlayerBlockCache[hash] = {
        userId = player.userId,
        postion = blockPos
    }
end

function BlockManager:onPlayerShootBlock(player, blockPos, gunId)
    local hash = VectorUtil.hashVector3(blockPos)
    local gun = GunConfig:getGunByItemId(gunId)
    if not gun then
        return
    end
    local life = BlockManager.BlockLifeCache[hash]
    if not life then
        return
    end
    life = life - gun.hurtBlock
    if life <= 0 then
        EngineWorld:setBlockToAir(blockPos)
        local pos = VectorUtil.newVector3(blockPos.x + 0.5, blockPos.y + 0.5, blockPos.z + 0.5)
        EngineWorld:addSimpleEffect("fragment_block.effect", pos, 0, 1000, 0, 2)
        BlockManager.BlockLifeCache[hash] = nil
        BlockManager.PlayerBlockCache[hash] = nil
    else
        BlockManager.BlockLifeCache[hash] = life
    end
end

return BlockManager