# user postion when enter game
initPos:
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5
    -
        x: 361.5
        y: 62.0
        z: 233.5

# show player position on client.
enableOutputPos: false

# is enable break block
enableBreak: false

# is enable break block
clearChestWhenMove: false

# is enable ouput inventroy pos
enableFindInventory: false

# player's items when enter game
initItems: {}

waitingPlayerTime: 150

# player can move during this time
disableMoveTime: 20

# parpare time by second
prepareTime: 30

# game time by second
gameTime: 420

# game over waiting time by second
gameOverTime: 30

# final fight start time by second
ffStartTime: 10

# final fight time by second
ffTime: 120

# final fight position
ffPos:
    -
        x: 128.5
        y: 124.0
        z: 122.5
    -
        x: 128.5
        y: 124.0
        z: 125.5
    -
        x: 131.5
        y: 124.0
        z: 125.5
    -
        x: 134.5
        y: 124.0
        z: 128.5
    -
        x: 132.5
        y: 124.0
        z: 128.5
    -
        x: 131.4
        y: 124.0
        z: 131.5
    -
        x: 128.5
        y: 124.0
        z: 134.6
    -
        x: 128.5
        y: 124.0
        z: 131.5
    -
        x: 128.5
        y: 124.0
        z: 128.5
    -
        x: 125.5
        y: 124.0
        z: 125.5
    -
        x: 125.5
        y: 124.0
        z: 128.5
    -
        x: 125.5
        y: 124.0
        z: 131.5
    -
        x: 122.4
        y: 124.0
        z: 128.5

# when to refresh inventory after start game in second
inventoryRefreshTime: 240

vipRandomItem: {276: 2}

# supper player item
sppItems: {314: 1, 315: 1, 316: 1, 317: 1, 279: 1}

# classes items
clzItems:
  0: {314: 1, 315: 1, 316: 1, 317: 1, 279: 1}
  1: {279: 1, 314: 1, 315: 1, 316: 1, 317: 1}
  2: {272: 1, 302: 1, 303: 1, 304: 1, 305: 1}
  3: {311: 1}
  4: {261: 1, 262: 15}
  5: {268: 1, 298: 1, 299: 1, 300: 1, 301: 1}
  6: {}
  7: {268: 1, 298: 1, 299: 1, 300: 1, 301: 1}
  8: {}
  9: {46: 3,  259: 1}
  10: {262: 15}

# Position of inventory that will generate vip item possibly
vipItemInventories:
          -
            x: 72.0
            y: 74.0
            z: 128.0
          -
            x: 69.0
            y: 73.0
            z: 163.0
          -
            x: 26.0
            y: 69.0
            z: 143.0
          -
            x: 30.0
            y: 68.0
            z: 145.0
          -
            x: 22.0
            y: 68.0
            z: 160.0
          -
            x: 41.0
            y: 69.0
            z: 209.0
          -
            x: 42.0
            y: 74.0
            z: 233.0
          -
            x: 91.0
            y: 70.0
            z: 211.0
          -
            x: 115.0
            y: 71.0
            z: 196.0
          -
            x: 120.0
            y: 73.0
            z: 229.0
          -
            x: 161.0
            y: 70.0
            z: 166.0
          -
            x: 175.0
            y: 73.0
            z: 132.0
          -
            x: 192.0
            y: 70.0
            z: 121.0
          -
            x: 233.0
            y: 76.0
            z: 146.0
          -
            x: 224.0
            y: 82.0
            z: 143.0
          -
            x: 226.0
            y: 73.0
            z: 149.0
          -
            x: 202.0
            y: 73.0
            z: 60.0
          -
            x: 207.0
            y: 73.0
            z: 81.0
          -
            x: 222.0
            y: 73.0
            z: 55.0
          -
            x: 197.0
            y: 72.0
            z: 81.0
          -
            x: 161.0
            y: 72.0
            z: 230.0
          -
            x: 163.0
            y: 71.0
            z: 200.0
          -
            x: 151.0
            y: 61.0
            z: 83.0
          -
            x: 167.0
            y: 72.0
            z: 82.0
          -
            x: 92.0
            y: 70.0
            z: 165.0
          -
            x: 129.0
            y: 70.0
            z: 178.0
          -
            x: 151.0
            y: 69.0
            z: 64.0
          -
            x: 108.0
            y: 72.0
            z: 54.0
          -
            x: 110.0
            y: 73.0
            z: 81.0
          -
            x: 96.0
            y: 74.0
            z: 93.0
          -
            x: 75.0
            y: 73.0
            z: 87.0
          -
            x: 18.0
            y: 66.0
            z: 48.0
          -
            x: 23.0
            y: 66.0
            z: 57.0
          -
            x: 76.0
            y: 66.0
            z: 85.0
          -
            x: 115.0
            y: 70.0
            z: 67.0
          -
            x: 96.0
            y: 70.0
            z: 39.0
          -
            x: 71.0
            y: 73.0
            z: 41.0
          -
            x: 103.0
            y: 66.0
            z: 105.0
          -
            x: 71.0
            y: 66.0
            z: 104.0
          -
            x: 130.0
            y: 74.0
            z: 95.0
          -
            x: 147.0
            y: 75.0
            z: 98.0
          -
            x: 94.0
            y: 72.0
            z: 127.0
          -
            x: 39.0
            y: 73.0
            z: 81.0
          -
            x: 35.0
            y: 75.0
            z: 70.0



# items in the inventory, and position of inventory
inventory:
    -
      fixedItems: {}
      # all range's first number must less than second
      foodNumRange: [1, 4]
      food:
          -
            id: 392
            randomRange: [5, 10]
            probability: 12
          -
            id: 319
            randomRange: [5, 10]
            probability: 8
          -
            id: 365
            randomRange: [5, 10]
            probability: 8
          -
            id: 260
            randomRange: [5, 10]
            probability: 8
          -
            id: 363
            randomRange: [5, 10]
            probability: 8
          -
            id: 391
            randomRange: [3, 8]
            probability: 8
          -
            id: 297
            randomRange: [3, 8]
            probability: 8
          -
            id: 366
            randomRange: [3, 8]
            probability: 8
          -
            id: 393
            randomRange: [3, 6]
            probability: 8
          -
            id: 320
            randomRange: [1, 5]
            probability: 8
          -
            id: 364
            randomRange: [1, 5]
            probability: 8
      equipNumRange: [2, 4]
      equip:
          -
            id: 298
            randomRange: [1, 2]
            probability: 9
          -
            id: 299
            randomRange: [1, 2]
            probability: 9
          -
            id: 300
            randomRange: [1, 2]
            probability: 9
          -
            id: 301
            randomRange: [1, 2]
            probability: 9
          -
            id: 314
            randomRange: [1, 2]
            probability: 7
          -
            id: 315
            randomRange: [1, 2]
            probability: 7
          -
            id: 316
            randomRange: [1, 2]
            probability: 7
          -
            id: 317
            randomRange: [1, 2]
            probability: 7
          -
            id: 302
            randomRange: [1, 2]
            probability: 5
          -
            id: 303
            randomRange: [1, 2]
            probability: 5
          -
            id: 304
            randomRange: [1, 2]
            probability: 5
          -
            id: 305
            randomRange: [1, 2]
            probability: 5
          -
            id: 306
            randomRange: [1, 2]
            probability: 4
          -
            id: 307
            randomRange: [1, 2]
            probability: 4
          -
            id: 308
            randomRange: [1, 2]
            probability: 4
          -
            id: 309
            randomRange: [1, 2]
            probability: 4
      weaponNumRange: [0, 2]
      weapon:
          -
            id: 268
            randomRange: [1, 2]
            probability: 18
          -
            id: 271
            randomRange: [1, 2]
            probability: 18
          -
            id: 283
            randomRange: [1, 2]
            probability: 14
          -
            id: 286
            randomRange: [1, 2]
            probability: 14
          -
            id: 272
            randomRange: [1, 2]
            probability: 10
          -
            id: 275
            randomRange: [1, 2]
            probability: 10
          -
            id: 267
            randomRange: [1, 1]
            probability: 8
          -
            id: 271
            randomRange: [1, 2]
            probability: 8
      materialsNumRange: [1, 3]
      materials:
          -
            id: 264
            randomRange: [1, 2]
            probability: 5
          -
            id: 265
            randomRange: [1, 2]
            probability: 15
          -
            id: 280
            randomRange: [5, 10]
            probability: 30
          -
            id: 259
            randomRange: [0, 1]
            probability: 15
          -
            id: 266
            randomRange: [1, 2]
            probability: 20
          -
            id: 325
            randomRange: [1, 2]
            probability: 15
      pos:
          -
            x: 128.0
            y: 72.0
            z: 129.0
          -
            x: 129.0
            y: 72.0
            z: 127.0
          -
            x: 126.0
            y: 72.0
            z: 127.0
          -
            x: 127.0
            y: 72.0
            z: 126.0
          -
            x: 130.0
            y: 80.0
            z: 125.0
          -
            x: 131.0
            y: 77.0
            z: 133.0
          -
            x: 121.0
            y: 78.0
            z: 130.0
          -
            x: 122.0
            y: 78.0
            z: 124.0
          -
            x: 72.0
            y: 74.0
            z: 128.0
          -
            x: 69.0
            y: 73.0
            z: 163.0
          -
            x: 26.0
            y: 69.0
            z: 143.0
          -
            x: 30.0
            y: 68.0
            z: 145.0
          -
            x: 22.0
            y: 68.0
            z: 160.0
          -
            x: 41.0
            y: 69.0
            z: 209.0
          -
            x: 42.0
            y: 74.0
            z: 233.0
          -
            x: 91.0
            y: 70.0
            z: 211.0
          -
            x: 115.0
            y: 71.0
            z: 196.0
          -
            x: 120.0
            y: 73.0
            z: 229.0
          -
            x: 161.0
            y: 70.0
            z: 166.0
          -
            x: 175.0
            y: 73.0
            z: 132.0
          -
            x: 192.0
            y: 70.0
            z: 121.0
          -
            x: 233.0
            y: 76.0
            z: 146.0
          -
            x: 224.0
            y: 82.0
            z: 143.0
          -
            x: 226.0
            y: 73.0
            z: 149.0
          -
            x: 202.0
            y: 73.0
            z: 60.0
          -
            x: 207.0
            y: 73.0
            z: 81.0
          -
            x: 222.0
            y: 73.0
            z: 55.0
          -
            x: 197.0
            y: 72.0
            z: 81.0
          -
            x: 161.0
            y: 72.0
            z: 230.0
          -
            x: 163.0
            y: 71.0
            z: 200.0
          -
            x: 151.0
            y: 61.0
            z: 83.0
          -
            x: 167.0
            y: 72.0
            z: 82.0
          -
            x: 92.0
            y: 70.0
            z: 165.0
          -
            x: 129.0
            y: 70.0
            z: 178.0
          -
            x: 151.0
            y: 69.0
            z: 64.0
          -
            x: 108.0
            y: 72.0
            z: 54.0
          -
            x: 110.0
            y: 73.0
            z: 81.0
          -
            x: 96.0
            y: 74.0
            z: 93.0
          -
            x: 75.0
            y: 73.0
            z: 87.0
          -
            x: 18.0
            y: 66.0
            z: 48.0
          -
            x: 23.0
            y: 66.0
            z: 57.0
          -
            x: 76.0
            y: 66.0
            z: 85.0
          -
            x: 115.0
            y: 70.0
            z: 67.0
          -
            x: 96.0
            y: 70.0
            z: 39.0
          -
            x: 71.0
            y: 73.0
            z: 41.0
          -
            x: 103.0
            y: 66.0
            z: 105.0
          -
            x: 71.0
            y: 66.0
            z: 104.0
          -
            x: 130.0
            y: 74.0
            z: 95.0
          -
            x: 147.0
            y: 75.0
            z: 98.0
          -
            x: 94.0
            y: 72.0
            z: 127.0
          -
            x: 39.0
            y: 73.0
            z: 81.0
          -
            x: 35.0
            y: 75.0
            z: 70.0
respawn:
    -
        time: 10
        price: [1, 5, 100]
        times: 3
    -
        time: 10
        price: [1, 10, 200]
        times: 2
    -
        time: 10
        price: [1, 30, 600]
        times: 1
        
#广告免费复活次数       
respawnAdMaxTimes: 1