---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2018/12/30 0030 11:02
---
GameFuncNpc = class()
GameFuncNpc.MODEL_SELECT = 13
GameFuncNpc.GUN_STORE = 14
GameFuncNpc.CHEST_LOTTERY = 15
GameFuncNpc.ARMOR_UPGRADE = 16
GameFuncNpc.SEASON_RANK = 17

function GameFuncNpc:ctor(config)
    self.players = {}
    self.type = tonumber(config.type)
    self.name = tostring(config.name)
    self.actor = tostring(config.actor) or ""
    self.pos = VectorUtil.newVector3(tonumber(config.x), tonumber(config.y), tonumber(config.z))
    self.yaw = tonumber(config.yaw) or 0
    self.effect = tostring(config.effect) or ""
    self:initArea(tonumber(config.range) or 1)
    self:onCreate()
end

function GameFuncNpc:initArea(range)
    self.minX = self.pos.x - range
    self.maxX = self.pos.x + range
    self.minY = self.pos.y - range
    self.maxY = self.pos.y + range
    self.minZ = self.pos.z - range
    self.maxZ = self.pos.z + range
end

function GameFuncNpc:onCreate()
    self.entityId = EngineWorld:addSessionNpc(self.pos, self.yaw, self.type, self.name, self.actor, "body")
    if self.effect ~= "" then
        EngineWorld:getWorld():setSessionNpcEffect(self.entityId, self.effect)
    end
end

function GameFuncNpc:inArea(x, y, z)
    return x >= self.minX and x <= self.maxX
            and y >= self.minY and y <= self.maxY
            and z >= self.minZ and z <= self.maxZ
end

function GameFuncNpc:onPlayerMove(player, x, y, z)
    if self:inArea(x, y, z) then
        self:onPlayerEnter(player)
    else
        self:onPlayerQuit(player)
    end
end

function GameFuncNpc:onPlayerEnter(player)
    if not self.players[tostring(player.userId)] then
        self.players[tostring(player.userId)] = true
        if self.type == GameFuncNpc.MODEL_SELECT then
            if DbUtil:CanSavePlayerData(player, DbUtil.GAME_DATA) then
                local data = player:getModeInfo()
                HostApi.sendOpenPixelGunHallModeSelect(player.rakssid, true, json.encode(data))
            end
        elseif self.type == GameFuncNpc.GUN_STORE then
            HostApi.sendShowGunStore(player.rakssid)
        elseif self.type == GameFuncNpc.CHEST_LOTTERY then
            HostApi.sendShowChestLottery(player.rakssid, true, player.chest_integral, ChestConfig:getUltimateChestIntegral())
        elseif self.type == GameFuncNpc.ARMOR_UPGRADE then
            GameArmor:sendOpenArmorUpgrade(player, true)
        elseif self.type == GameFuncNpc.SEASON_RANK then
            HostApi.sendShowSeasonRank(player.rakssid)
        end
    end
end

function GameFuncNpc:onPlayerQuit(player)
    self.players[tostring(player.userId)] = nil
end