---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jimmy.
--- DateTime: 2019/1/16 0016 11:33
---
GameAppShop = {}
GameAppShop.GoodsType = {
    GOLD = 1,
    GUN_CHIP = 2,
    PROP_CHIP = 3,
    CHEST = 4,
    KEY = 5,
    VIP = 6
}

function GameAppShop:onPlayerShopping(player, goodsId)
    local goods = AppShopConfig:getGoodsById(goodsId)
    if not goods then
        return false
    end
    local money = 0
    if goods.PriceType == Define.Money.DIAMOND then
        money = player:getDiamond()
    end
    if goods.PriceType == Define.Money.GOLD then
        money = player:getGold()
    end
    if goods.PriceType == Define.Money.MONEY then
        money = player.money
    end
    if money < goods.Price then
        return false
    end
    if goods.Type == GameAppShop.GoodsType.GOLD then
        GameAppShop:onPlayerBuyGold(player, goods)
    end
    if goods.Type == GameAppShop.GoodsType.GUN_CHIP then
        GameAppShop:onPlayerBuyGunChip(player, goods)
    end
    if goods.Type == GameAppShop.GoodsType.PROP_CHIP then
        GameAppShop:onPlayerBuyPropChip(player, goods)
    end
    if goods.Type == GameAppShop.GoodsType.CHEST then
        GameAppShop:onPlayerBuyChest(player, goods)
    end
    if goods.Type == GameAppShop.GoodsType.KEY then
        GameAppShop:onPlayerBuyKey(player, goods)
    end
    if goods.Type == GameAppShop.GoodsType.VIP then
        GameAppShop:onPlayerBuyVip(player, goods)
    end
    return false
end

function GameAppShop:onPlayerBuyGold(player, goods)
    player:addCurrency(goods.Count)
end

function GameAppShop:onPlayerBuyGunChip(player, goods)
    GameChestLottery:onPlayerRewardGunChip(player, goods.RealId, goods.Count)
    HostApi.notifyGetGoods(player.rakssid, goods.Icon, goods.Count)
end

function GameAppShop:onPlayerBuyPropChip(player, goods)
    GameChestLottery:onPlayerRewardPropChip(player, goods.RealId, goods.Count)
    HostApi.notifyGetGoods(player.rakssid, goods.Icon, goods.Count)
end

function GameAppShop:onPlayerBuyChest(player, goods)
    GameChestLottery:addPlayerLotteryChest(player, goods.RealId, goods.Count)
    HostApi.notifyGetGoods(player.rakssid, goods.Icon, goods.Count)
end

function GameAppShop:onPlayerBuyKey(player, goods)
    player.yaoshi = player.yaoshi + goods.Count
    player:syncHallInfo()
    HostApi.notifyGetGoods(player.rakssid, goods.Icon, goods.Count)
end

function GameAppShop:onPlayerBuyVip(player, goods)
    GameChestLottery:onPlayerRewardVip(player, goods.Time)
    HostApi.notifyGetGoods(player.rakssid, goods.Icon, goods.Count)
end

return GameAppShop