---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/24 18:50
---
CustomListener = {}

function CustomListener:init()
    ConsumeTipMsgEvent.registerCallBack(self.onConsumeTipMsg)
    ConsumeDiamondsEvent.registerCallBack(self.onConsumeDiamonds)
end

function CustomListener.onConsumeTipMsg(rakssid, extra, isRight)
    if isRight == false then
        return
    end
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if player == nil then
        return
    end
    local info = StringUtil.split(extra, "#")
    if #info == 2 then
        local extra1 = tostring(info[1])
        local extra2 = tonumber(info[2])
        if extra1 == Define.OpenLotteryChest then
            GameChestLottery:onPlayerConfirmPayLottery(player, extra2)
            return
        end
    end
end

function CustomListener.onConsumeDiamonds(rakssid, isSuccess, message, extra)
    if isSuccess == false then
        return
    end
    local player = PlayerManager:getPlayerByRakssid(rakssid)
    if player == nil then
        return
    end
    local info = StringUtil.split(extra, "#")
    if #info == 2 then
        local extra1 = tostring(info[1])
        local extra2 = tonumber(info[2])
        if extra1 == Define.UnlockMap then
            player:unlockMap(extra2)
            local data = player:getModeInfo()
            HostApi.sendOpenPixelGunHallModeSelect(rakssid, true, json.encode(data))
            return
        end
        if extra1 == Define.BuyGun then
            GameGunStore:onBuyStoreGunSuccess(player, extra2)
            return
        end
        if extra1 == Define.UpgradeGun then
            GameGunStore:onUpgradeStoreGunSuccess(player, extra2)
            return
        end
        if extra1 == Define.QuickUpgradeGun then
            GameGunStore:onQuickUpgradeStoreGunSuccess(player, extra2)
            return
        end
        if extra1 == Define.BuyProp then
            GameGunStore:onBuyStorePropSuccess(player, extra2)
            return
        end
        if extra1 == Define.UpgradeProp then
            GameGunStore:onUpgradeStorePropSuccess(player, extra2)
            return
        end
        if extra1 == Define.QuickUpgradeProp then
            GameGunStore:onQuickUpgradeStorePropSuccess(player, extra2)
            return
        end
        if extra1 == Define.OpenLotteryChest then
            GameChestLottery:onPlayerLottery(player, extra2)
            return
        end

        if extra1 == Define.UpArmor then
            GameArmor:armorUping(player, extra2)
            return
        end

        if extra1 == Define.SpeedUpGradeArmor then
            GameArmor:quickUpgradeArmorFinished(player, extra2)
        end
    end
end

return CustomListener