---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/19 11:18
---

DBUtil = {}

function DBUtil:getPlayerData(player)
    DBManager:getPlayerData(player.userId, 2)
end

function DBUtil:saveAllPlayerData()
    local players = PlayerManager:getPlayers()
    for _, player in pairs(players) do
        self:savePlayerData(player, true)
    end
end

function DBUtil:savePlayerData(player, immediate)
    if player == nil then
        return
    end
    if player.isReady == false then
        return
    end
    local data = {}
    data.money = player.hallMoney
    DBManager:savePlayerData(player.userId, 2, json.encode(data), immediate)
end