---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2018/9/12 14:46
---

require "Match"

DBDataListener = {}

function DBDataListener:init()
    BaseListener.registerCallBack(GetDataFromDBEvent, self.onGetDataFromBD)
end

function DBDataListener.onGetDataFromBD(player, subKey, data)
    player:initDataFromDB(data)
end

return DBDataListener