name: Run Game Server

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  run-server:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run runserver.bat
      run: call runserver.bat
