name: Run Game Server via BAT

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-server:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Game Server via BAT
      run: |
        echo "Running start_server.bat..."
        start runserver.bat
