name: Run Game Server via BAT

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Game Server via BAT
      shell: cmd
      run: runserver.bat
